# Generated by Django 4.2.9 on 2024-01-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=100)),
                ('price', models.TextField()),
                ('technology', models.CharField(max_length=20)),
            ],
        ),
    ]
