# Generated by Django 4.2.9 on 2024-01-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_dailyprice_close_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
